require("arc/options")
require("arc/keymaps")
require("arc/plugins")
require("arc/colorscheme")
require("arc/comment")
require("arc/autopairs")
require("arc/surround")
require("arc/treesitter")
require("arc/statusline")
require("arc/oil")
require("arc/bufline")
-- require("arc/lspconfig")
-- require("arc/cmp")
require("arc/mason")
